# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='hello', unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together=set([('title', 'slug')]),
        ),
    ]
